local function set_colors()
  -- Highlight groups
  local hi = vim.api.nvim_set_hl

  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@constant.builtin", { link = "Special" })
  hi(0, "@constant.macro", { link = "Define" })
  hi(0, "@function.builtin", { link = "Special" })
  hi(0, "@function.macro", { link = "Macro" })
  hi(0, "@keyword.return", { fg = "#ccc3e4" })
  hi(0, "@lsp.mod.defaultLibrary", { link = "Special" })
  hi(0, "@lsp.mod.deprecated", { fg = "#ccc3e4" })
  hi(0, "@lsp.type.class", { link = "Structure" })
  hi(0, "@lsp.type.comment", { link = "Comment" })
  hi(0, "@lsp.type.decorator", { link = "Function" })
  hi(0, "@lsp.type.enum", { link = "Structure" })
  hi(0, "@lsp.type.enumMember", { link = "Constant" })
  hi(0, "@lsp.type.function", { link = "Function" })
  hi(0, "@lsp.type.interface", { link = "Structure" })
  hi(0, "@lsp.type.macro", { link = "Macro" })
  hi(0, "@lsp.type.method", { link = "Function" })
  hi(0, "@lsp.type.namespace", { link = "Structure" })
  hi(0, "@lsp.type.parameter", { link = "Identifier" })
  hi(0, "@lsp.type.property", { link = "Identifier" })
  hi(0, "@lsp.type.struct", { link = "Structure" })
  hi(0, "@lsp.type.type", { link = "Type" })
  hi(0, "@lsp.type.typeParameter", { link = "Typedef" })
  hi(0, "@lsp.type.variable", { fg = "#c0aef4" })
  hi(0, "@string.escape", { link = "SpecialChar" })
  hi(0, "@string.special", { link = "SpecialChar" })
  hi(0, "@symbol", { fg = "#fdb5a8" })
  hi(0, "@text.emphasis", { italic = true })
  hi(0, "@text.literal", { link = "Comment" })
  hi(0, "@text.reference", { link = "Identifier" })
  hi(0, "@text.strike", { strikethrough = true })
  hi(0, "@text.strong", { bold = true })
  hi(0, "@text.title", { link = "Title" })
  hi(0, "@text.todo", { link = "Todo" })
  hi(0, "@text.underline", { link = "Underlined" })
  hi(0, "@text.uri", { link = "Underlined" })
  hi(0, "@type.definition", { link = "Typedef" })
  hi(0, "@variable", { fg = "#c0aef4" })
  hi(0, "Beacon", { bg = "#806d91" })
  hi(0, "Bold", { bold = true })
  hi(0, "Boolean", { fg = "#88cfdf" })
  hi(0, "BufferAlternate", {})
  hi(0, "BufferAlternateADDED", {})
  hi(0, "BufferAlternateCHANGED", {})
  hi(0, "BufferAlternateDELETED", {})
  hi(0, "BufferAlternateERROR", {})
  hi(0, "BufferAlternateHINT", {})
  hi(0, "BufferAlternateINFO", {})
  hi(0, "BufferAlternateIcon", {})
  hi(0, "BufferAlternateIndex", {})
  hi(0, "BufferAlternateMod", {})
  hi(0, "BufferAlternateNumber", {})
  hi(0, "BufferAlternateSign", {})
  hi(0, "BufferAlternateSignRight", {})
  hi(0, "BufferAlternateTarget", {})
  hi(0, "BufferAlternateWARN", {})
  hi(0, "BufferCurrent", { bg = "#161027", bold = true, fg = "#c0aef4" })
  hi(0, "BufferCurrentADDED", { bg = "#241e35", ctermfg = 82, fg = "#f8c379" })
  hi(0, "BufferCurrentCHANGED", { bg = "#241e35", ctermfg = 75, fg = "#fdb5a8" })
  hi(0, "BufferCurrentDELETED", { bg = "#241e35", ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferCurrentERROR", { bg = "#241e35", ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferCurrentHINT", { bg = "#241e35", ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferCurrentINFO", { bg = "#241e35", ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferCurrentIcon", { bg = "#161027" })
  hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
  hi(0, "BufferCurrentMod", { bg = "#161027", bold = true, fg = "#ccc3e4" })
  hi(0, "BufferCurrentNumber", { bg = "#161027" })
  hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
  hi(0, "BufferCurrentSignRight", { bg = "#161027", bold = true, fg = "#c0aef4" })
  hi(0, "BufferCurrentTarget", { bg = "#161027", bold = true, fg = "#fdb5a8" })
  hi(0, "BufferCurrentWARN", { bg = "#241e35", ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultAlternateIcon", {})
  hi(0, "BufferDefaultAlternateNumber", {})
  hi(0, "BufferDefaultAlternateSignRight", {})
  hi(0, "BufferDefaultCurrent", { bg = "#241e35", ctermfg = 255, fg = "#f8c379" })
  hi(0, "BufferDefaultCurrentADDED", { bg = "#241e35", ctermfg = 82, fg = "#f8c379" })
  hi(0, "BufferDefaultCurrentCHANGED", { bg = "#241e35", ctermfg = 75, fg = "#fdb5a8" })
  hi(0, "BufferDefaultCurrentDELETED", { bg = "#241e35", ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferDefaultCurrentERROR", { bg = "#241e35", ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferDefaultCurrentHINT", { bg = "#241e35", ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferDefaultCurrentINFO", { bg = "#241e35", ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferDefaultCurrentIcon", { bg = "#161027", bold = true, fg = "#c0aef4" })
  hi(0, "BufferDefaultCurrentIndex", { bg = "#241e35", ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "BufferDefaultCurrentMod", { bg = "#241e35", ctermfg = 224, fg = "#ccc3e4" })
  hi(0, "BufferDefaultCurrentNumber", { bg = "#161027" })
  hi(0, "BufferDefaultCurrentSign", { bg = "#241e35", ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "BufferDefaultCurrentSignRight", { bg = "#161027", bold = true, fg = "#c0aef4" })
  hi(0, "BufferDefaultCurrentTarget", { bg = "#241e35", bold = true, ctermfg = 9, fg = "#ff0000" })
  hi(0, "BufferDefaultCurrentWARN", { bg = "#241e35", ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultInactive", { bg = "#241e35", ctermbg = 242, ctermfg = 15, fg = "#7a7094" })
  hi(0, "BufferDefaultInactiveADDED", { bg = "#241e35", ctermbg = 242, ctermfg = 82, fg = "#f8c379" })
  hi(0, "BufferDefaultInactiveCHANGED", { bg = "#241e35", ctermbg = 242, ctermfg = 75, fg = "#fdb5a8" })
  hi(0, "BufferDefaultInactiveDELETED", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferDefaultInactiveERROR", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferDefaultInactiveHINT", { bg = "#241e35", ctermbg = 242, ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferDefaultInactiveINFO", { bg = "#241e35", ctermbg = 242, ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferDefaultInactiveIcon", { bg = "#241e35", fg = "#8ba4e5" })
  hi(0, "BufferDefaultInactiveIndex", { bg = "#241e35", ctermbg = 242, ctermfg = 12, fg = "#7a7094" })
  hi(0, "BufferDefaultInactiveMod", { bg = "#241e35", ctermbg = 242, ctermfg = 224, fg = "#ccc3e4" })
  hi(0, "BufferDefaultInactiveNumber", { bg = "#241e35" })
  hi(0, "BufferDefaultInactiveSign", { bg = "#241e35", ctermbg = 242, ctermfg = 12, fg = "#7a7094" })
  hi(0, "BufferDefaultInactiveSignRight", { bg = "#241e35", fg = "#8ba4e5" })
  hi(0, "BufferDefaultInactiveTarget", { bg = "#241e35", bold = true, ctermbg = 242, ctermfg = 9, fg = "#ff0000" })
  hi(0, "BufferDefaultInactiveWARN", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultOffset", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "BufferDefaultTabpageFill", { bg = "#241e35", ctermfg = 102, fg = "#7a7094" })
  hi(0, "BufferDefaultTabpages", { bg = "#241e35", bold = true, ctermfg = 75, fg = "#88cfdf" })
  hi(0, "BufferDefaultTabpagesSep", { bg = "#241e35", bold = true, ctermfg = 255, fg = "#c1b7de" })
  hi(0, "BufferDefaultVisible", { bg = "#241e35", ctermbg = 242, ctermfg = 15, fg = "#7a7094" })
  hi(0, "BufferDefaultVisibleADDED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultVisibleCHANGED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultVisibleDELETED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferDefaultVisibleERROR", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferDefaultVisibleHINT", { bg = "#241e35", ctermbg = 242, ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferDefaultVisibleINFO", { bg = "#241e35", ctermbg = 242, ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferDefaultVisibleIcon", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "BufferDefaultVisibleIndex", { bg = "#241e35", ctermbg = 242, ctermfg = 15, fg = "#7a7094" })
  hi(0, "BufferDefaultVisibleMod", { bg = "#241e35", ctermbg = 242, ctermfg = 224, fg = "#ccc3e4" })
  hi(0, "BufferDefaultVisibleNumber", { bg = "#241e35" })
  hi(0, "BufferDefaultVisibleSign", { bg = "#241e35", ctermbg = 242, ctermfg = 15, fg = "#7a7094" })
  hi(0, "BufferDefaultVisibleSignRight", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "BufferDefaultVisibleTarget", { bg = "#241e35", bold = true, ctermbg = 242, ctermfg = 9, fg = "#ff0000" })
  hi(0, "BufferDefaultVisibleWARN", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferInactive", { bg = "#241e35", fg = "#8ba4e5" })
  hi(0, "BufferInactiveADDED", { bg = "#241e35", ctermbg = 242, ctermfg = 82, fg = "#f8c379" })
  hi(0, "BufferInactiveCHANGED", { bg = "#241e35", ctermbg = 242, ctermfg = 75, fg = "#fdb5a8" })
  hi(0, "BufferInactiveDELETED", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferInactiveERROR", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferInactiveHINT", { bg = "#241e35", ctermbg = 242, ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferInactiveINFO", { bg = "#241e35", ctermbg = 242, ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferInactiveIcon", { bg = "#241e35" })
  hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
  hi(0, "BufferInactiveMod", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "BufferInactiveNumber", { bg = "#241e35" })
  hi(0, "BufferInactiveSign", { link = "BufferInactive" })
  hi(0, "BufferInactiveSignRight", { bg = "#241e35", fg = "#8ba4e5" })
  hi(0, "BufferInactiveTarget", { bg = "#241e35", bold = true, fg = "#fdb5a8" })
  hi(0, "BufferInactiveWARN", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferLineBuffer", { fg = "#8ba4e5" })
  hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c0aef4" })
  hi(0, "BufferLineBufferVisible", { fg = "#c0aef4" })
  hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
  hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
  hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
  hi(0, "BufferLineFill", { link = "Normal" })
  hi(0, "BufferLineTab", { bg = "#93d1b5", fg = "#1d172f" })
  hi(0, "BufferLineTabSelected", { bg = "#93d1b5", bold = true, fg = "#1d172f" })
  hi(0, "BufferOffset", { link = "Normal" })
  hi(0, "BufferScrollArrow", { bg = "#241e35", bold = true, ctermfg = 255, fg = "#c1b7de" })
  hi(0, "BufferTabpageFill", { link = "Normal" })
  hi(0, "BufferTabpages", { bg = "#93d1b5", bold = true, fg = "#241e35" })
  hi(0, "BufferTabpagesSep", { bg = "#241e35", bold = true, ctermfg = 255, fg = "#c1b7de" })
  hi(0, "BufferVisible", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "BufferVisibleADDED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferVisibleCHANGED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferVisibleDELETED", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "BufferVisibleERROR", { bg = "#241e35", ctermbg = 242, ctermfg = 124, fg = "#ccc3e4" })
  hi(0, "BufferVisibleHINT", { bg = "#241e35", ctermbg = 242, ctermfg = 168, fg = "#f0b0d8" })
  hi(0, "BufferVisibleINFO", { bg = "#241e35", ctermbg = 242, ctermfg = 217, fg = "#9bc3f6" })
  hi(0, "BufferVisibleIcon", { bg = "#241e35" })
  hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
  hi(0, "BufferVisibleMod", { bg = "#241e35", bold = true, fg = "#ccc3e4" })
  hi(0, "BufferVisibleNumber", { bg = "#241e35" })
  hi(0, "BufferVisibleSign", { link = "BufferVisible" })
  hi(0, "BufferVisibleSignRight", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "BufferVisibleTarget", { bg = "#241e35", bold = true, fg = "#fdb5a8" })
  hi(0, "BufferVisibleWARN", { bg = "#241e35", ctermbg = 242, ctermfg = 208, fg = "#fdb5a8" })
  hi(0, "Character", { fg = "#ccc3e4" })
  hi(0, "CmpItemAbbr", { fg = "#c0aef4" })
  hi(0, "CmpItemAbbrDeprecated", { fg = "#7a7094" })
  hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#93d1b5" })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#93d1b5" })
  hi(0, "CmpItemKind", { bg = "#241e35", fg = "#c1b7de" })
  hi(0, "CmpItemKindClass", { link = "Type" })
  hi(0, "CmpItemKindColor", { link = "Special" })
  hi(0, "CmpItemKindConstant", { link = "Constant" })
  hi(0, "CmpItemKindConstructor", { link = "Type" })
  hi(0, "CmpItemKindEnum", { link = "Structure" })
  hi(0, "CmpItemKindEnumMember", { link = "Structure" })
  hi(0, "CmpItemKindEvent", { link = "Exception" })
  hi(0, "CmpItemKindField", { link = "Structure" })
  hi(0, "CmpItemKindFile", { link = "Tag" })
  hi(0, "CmpItemKindFolder", { link = "Directory" })
  hi(0, "CmpItemKindFunction", { link = "Function" })
  hi(0, "CmpItemKindInterface", { link = "Structure" })
  hi(0, "CmpItemKindKeyword", { link = "Keyword" })
  hi(0, "CmpItemKindMethod", { link = "Function" })
  hi(0, "CmpItemKindModule", { link = "Structure" })
  hi(0, "CmpItemKindOperator", { link = "Operator" })
  hi(0, "CmpItemKindProperty", { link = "Structure" })
  hi(0, "CmpItemKindReference", { link = "Tag" })
  hi(0, "CmpItemKindSnippet", { link = "Special" })
  hi(0, "CmpItemKindStruct", { link = "Structure" })
  hi(0, "CmpItemKindText", { link = "Statement" })
  hi(0, "CmpItemKindTypeParameter", { link = "Type" })
  hi(0, "CmpItemKindUnit", { link = "Special" })
  hi(0, "CmpItemKindValue", { link = "Identifier" })
  hi(0, "CmpItemKindVariable", { link = "Delimiter" })
  hi(0, "CmpItemMenu", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "CocCodeLens", { link = "LspCodeLens" })
  hi(0, "CocDisabled", { link = "Comment" })
  hi(0, "CocErrorFloat", { link = "DiagnosticFloatingError" })
  hi(0, "CocErrorHighlight", { link = "DiagnosticError" })
  hi(0, "CocErrorSign", { link = "DiagnosticSignError" })
  hi(0, "CocHintFloat", { link = "DiagnosticFloatingHint" })
  hi(0, "CocHintHighlight", { link = "DiagnosticHint" })
  hi(0, "CocHintSign", { link = "DiagnosticSignHint" })
  hi(0, "CocInfoFloat", { link = "DiagnosticFloatingInfo" })
  hi(0, "CocInfoHighlight", { link = "DiagnosticInfo" })
  hi(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
  hi(0, "CocMarkdownLink", { fg = "#c1b7de" })
  hi(0, "CocMenuSel", { bg = "#161027" })
  hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
  hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
  hi(0, "CocSearch", { fg = "#93d1b5" })
  hi(0, "CocSelectedText", { fg = "#ccc3e4" })
  hi(0, "CocWarningFloat", { link = "DiagnosticFloatingWarn" })
  hi(0, "CocWarningHighlight", { link = "DiagnosticWarn" })
  hi(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
  hi(0, "ColorColumn", { bg = "#241e35", ctermbg = 1 })
  hi(0, "Comment", { ctermfg = 14, fg = "#7a7094" })
  hi(0, "Conceal", { ctermbg = 242, ctermfg = 7, fg = "#f0b0d8" })
  hi(0, "Conditional", { fg = "#fdb5a8" })
  hi(0, "Constant", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "CurSearch", { bg = "#88cfdf", fg = "#241e35" })
  hi(0, "Cursor", { bg = "#c0aef4", fg = "#1d172f" })
  hi(0, "CursorColumn", { bg = "#241e35", ctermbg = 242 })
  hi(0, "CursorIM", { bg = "#c0aef4", fg = "#1d172f" })
  hi(0, "CursorLine", { bg = "#241e35" })
  hi(0, "CursorLineFold", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "CursorLineNr", { bg = "#241e35", ctermfg = 11, fg = "#8ba4e5" })
  hi(0, "CursorLineSign", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#f8c379" })
  hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
  hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
  hi(0, "DapUIBreakpointsPath", { link = "Directory" })
  hi(0, "DapUIDecoration", { link = "Title" })
  hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
  hi(0, "DapUILineNumber", { link = "Title" })
  hi(0, "DapUIModifiedValue", { bold = true, fg = "#fdb5a8" })
  hi(0, "DapUIScope", { link = "Title" })
  hi(0, "DapUISource", { link = "Directory" })
  hi(0, "DapUIStoppedThread", { link = "Title" })
  hi(0, "DapUIThread", { link = "String" })
  hi(0, "DapUIType", { link = "Type" })
  hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
  hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
  hi(0, "DapUIWatchesValue", { link = "String" })
  hi(0, "DashboardCenter", { link = "Delimiter" })
  hi(0, "DashboardFooter", { link = "Title" })
  hi(0, "DashboardHeader", { link = "Title" })
  hi(0, "DashboardShortCut", { link = "WarningMsg" })
  hi(0, "Debug", { fg = "#ccc3e4" })
  hi(0, "Define", { fg = "#fdb5a8" })
  hi(0, "Definitions", { fg = "#f8c379" })
  hi(0, "DefinitionsIcon", { fg = "#f0b0d8" })
  hi(0, "Delimiter", { fg = "#c1b7de" })
  hi(0, "DiagnosticError", { ctermfg = 1, fg = "#ccc3e4" })
  hi(0, "DiagnosticFloatingError", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "DiagnosticFloatingHint", { bg = "#241e35", fg = "#f0b0d8" })
  hi(0, "DiagnosticFloatingInfo", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "DiagnosticFloatingOk", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "DiagnosticFloatingWarn", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "DiagnosticHint", { ctermfg = 7, fg = "#f0b0d8" })
  hi(0, "DiagnosticInfo", { ctermfg = 4, fg = "#9bc3f6" })
  hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#f8c379" })
  hi(0, "DiagnosticSignError", { link = "DiagnosticFloatingError" })
  hi(0, "DiagnosticSignHint", { link = "DiagnosticFloatingHint" })
  hi(0, "DiagnosticSignInfo", { link = "DiagnosticFloatingInfo" })
  hi(0, "DiagnosticSignOk", { link = "DiagnosticFloatingOk" })
  hi(0, "DiagnosticSignWarn", { link = "DiagnosticFloatingWarn" })
  hi(0, "DiagnosticUnderlineError", { sp = "#ccc3e4", underline = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#f0b0d8", underline = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#9bc3f6", underline = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#f8c379", underline = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#fdb5a8", underline = true })
  hi(0, "DiagnosticWarn", { ctermfg = 3, fg = "#fdb5a8" })
  hi(0, "DiffAdd", { bg = "#241e35", ctermbg = 4, fg = "#f8c379" })
  hi(0, "DiffAdded", { bg = "#1d172f", fg = "#f8c379" })
  hi(0, "DiffChange", { bg = "#241e35", ctermbg = 5, fg = "#fdb5a8" })
  hi(0, "DiffDelete", { bg = "#241e35", ctermbg = 6, ctermfg = 12, fg = "#ccc3e4" })
  hi(0, "DiffFile", { bg = "#1d172f", fg = "#ccc3e4" })
  hi(0, "DiffLine", { bg = "#1d172f", fg = "#f0b0d8" })
  hi(0, "DiffNewFile", { link = "DiffAdded" })
  hi(0, "DiffRemoved", { link = "DiffFile" })
  hi(0, "DiffText", { bg = "#241e35", ctermbg = 9, fg = "#f0b0d8" })
  hi(0, "Directory", { ctermfg = 159, fg = "#f0b0d8" })
  hi(0, "EndOfBuffer", { blend = 0, fg = "#7a7094" })
  hi(0, "Error", { bg = "#ccc3e4", ctermbg = 9, ctermfg = 15, fg = "#1d172f" })
  hi(0, "ErrorMsg", { bg = "#1d172f", ctermbg = 1, ctermfg = 15, fg = "#ccc3e4" })
  hi(0, "Exception", { fg = "#ccc3e4" })
  hi(0, "FinderParam", { fg = "#ccc3e4" })
  hi(0, "FinderSpinner", { fg = "#f8c379" })
  hi(0, "FinderSpinnerBorder", { fg = "#c1b7de" })
  hi(0, "FinderSpinnerTitle", { link = "Title" })
  hi(0, "FinderVirtText", { fg = "#88cfdf" })
  hi(0, "Float", { fg = "#88cfdf" })
  hi(0, "FoldColumn", { bg = "#241e35", ctermbg = 242, ctermfg = 14, fg = "#9bc3f6" })
  hi(0, "Folded", { bg = "#241e35", ctermbg = 242, ctermfg = 14, fg = "#7a7094" })
  hi(0, "Function", { fg = "#f0b0d8" })
  hi(0, "GitSignsAdd", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
  hi(0, "GitSignsAddLnInline", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "GitSignsAddNr", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "GitSignsAddPreview", { bg = "#241e35", ctermbg = 4, fg = "#f8c379" })
  hi(0, "GitSignsChange", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
  hi(0, "GitSignsChangeLnInline", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsChangeNr", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsChangedelete", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsChangedeleteLn", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsChangedeleteNr", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "GitSignsCurrentLineBlame", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "GitSignsDelete", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
  hi(0, "GitSignsDeleteLnInline", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsDeleteNr", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsDeletePreview", { bg = "#241e35", ctermbg = 6, ctermfg = 12, fg = "#ccc3e4" })
  hi(0, "GitSignsDeleteVirtLn", { bg = "#241e35", ctermbg = 6, ctermfg = 12, fg = "#ccc3e4" })
  hi(0, "GitSignsDeleteVirtLnInLine", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsStagedAdd", { bg = "#241e35", fg = "#7c613c" })
  hi(0, "GitSignsStagedAddLn", { bg = "#241e35", fg = "#7c613c" })
  hi(0, "GitSignsStagedAddNr", { bg = "#241e35", fg = "#7c613c" })
  hi(0, "GitSignsStagedChange", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedChangeLn", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedChangeNr", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedChangedelete", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedChangedeleteLn", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedChangedeleteNr", { bg = "#241e35", fg = "#7e5a54" })
  hi(0, "GitSignsStagedDelete", { bg = "#241e35", fg = "#666172" })
  hi(0, "GitSignsStagedDeleteLn", { bg = "#241e35", fg = "#666172" })
  hi(0, "GitSignsStagedDeleteNr", { bg = "#241e35", fg = "#666172" })
  hi(0, "GitSignsStagedTopdelete", { bg = "#241e35", fg = "#666172" })
  hi(0, "GitSignsStagedTopdeleteNr", { bg = "#241e35", fg = "#666172" })
  hi(0, "GitSignsTopdelete", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsTopdeleteNr", { bg = "#241e35", fg = "#ccc3e4" })
  hi(0, "GitSignsUntracked", { bg = "#241e35", fg = "#f0b0d8" })
  hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
  hi(0, "GitSignsUntrackedNr", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "HopNextKey", { bold = true, fg = "#fdb5a8", nocombine = true })
  hi(0, "HopNextKey1", { bold = true, fg = "#ccc3e4", nocombine = true })
  hi(0, "HopNextKey2", { bold = true, fg = "#8ba4e5", nocombine = true })
  hi(0, "HopPreview", { bold = true, fg = "#88cfdf", nocombine = true })
  hi(0, "HopUnmatched", { link = "Comment" })
  hi(0, "HydraAmaranth", { fg = "#fdb5a8" })
  hi(0, "HydraBlue", { fg = "#f0b0d8" })
  hi(0, "HydraHint", { link = "NormalFloat" })
  hi(0, "HydraPink", { fg = "#88cfdf" })
  hi(0, "HydraRed", { fg = "#ccc3e4" })
  hi(0, "HydraTeal", { fg = "#f8c379" })
  hi(0, "Identifier", { ctermfg = 14, fg = "#ccc3e4" })
  hi(0, "Ignore", { ctermfg = 0, fg = "#9bc3f6" })
  hi(0, "IncSearch", { bg = "#88cfdf", fg = "#241e35" })
  hi(0, "Include", { fg = "#f0b0d8" })
  hi(0, "IndentBlanklineChar", { fg = "#161027", nocombine = true })
  hi(0, "IndentBlanklineContextChar", { fg = "#c1b7de", nocombine = true })
  hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#c1b7de", underline = true })
  hi(0, "IndentBlanklineIndent1", { fg = "#ccc3e4", nocombine = true })
  hi(0, "IndentBlanklineIndent2", { fg = "#88cfdf", nocombine = true })
  hi(0, "IndentBlanklineIndent3", { fg = "#93d1b5", nocombine = true })
  hi(0, "IndentBlanklineIndent4", { fg = "#f8c379", nocombine = true })
  hi(0, "IndentBlanklineIndent5", { fg = "#9bc3f6", nocombine = true })
  hi(0, "IndentBlanklineIndent6", { fg = "#f0b0d8", nocombine = true })
  hi(0, "IndentBlanklineIndent7", { fg = "#fdb5a8", nocombine = true })
  hi(0, "IndentBlanklineIndent8", { fg = "#c1b7de", nocombine = true })
  hi(0, "Italic", { italic = true })
  hi(0, "Keyword", { fg = "#fdb5a8" })
  hi(0, "LSOutlinePreviewBorder", { fg = "#c1b7de" })
  hi(0, "Label", { fg = "#93d1b5" })
  hi(0, "LazyButton", { bg = "#241e35" })
  hi(0, "LazyButtonActive", { bg = "#161027" })
  hi(0, "LazyDimmed", { link = "Comment" })
  hi(0, "LazyH1", { bg = "#161027", bold = true })
  hi(0, "LeapBackdrop", { link = "Comment" })
  hi(0, "LeapLabelPrimary", { bold = true, fg = "#ccc3e4", nocombine = true })
  hi(0, "LeapLabelSecondary", { bold = true, fg = "#c0aef4", nocombine = true })
  hi(0, "LeapLabelSelected", { bold = true, fg = "#88cfdf", nocombine = true })
  hi(0, "LeapMatch", { bold = true, fg = "#fdb5a8", nocombine = true })
  hi(0, "LightspeedCursor", { link = "Cursor" })
  hi(0, "LightspeedGreyWash", { link = "Comment" })
  hi(0, "LightspeedLabel", { bold = true, fg = "#fdb5a8", underline = true })
  hi(0, "LightspeedLabelDistant", { bold = true, fg = "#f0b0d8", underline = true })
  hi(0, "LightspeedMaskedChar", { fg = "#8ba4e5" })
  hi(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
  hi(0, "LightspeedPendingOpArea", { link = "IncSearch" })
  hi(0, "LightspeedShortcut", { bold = true, fg = "#806d91" })
  hi(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
  hi(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#c0aef4" })
  hi(0, "LineNr", { bg = "#241e35", ctermfg = 11, fg = "#7a7094" })
  hi(0, "LineNrAbove", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "LineNrBelow", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "LspCodeLens", { link = "Comment" })
  hi(0, "LspCodeLensSeparator", { link = "Comment" })
  hi(0, "LspInfoBorder", { fg = "#93d1b5" })
  hi(0, "LspInfoFiletype", { ctermfg = 121, fg = "#93d1b5" })
  hi(0, "LspInfoList", { fg = "#f0b0d8" })
  hi(0, "LspInfoTip", { ctermfg = 14, fg = "#7a7094" })
  hi(0, "LspInfoTitle", { ctermfg = 225, fg = "#f0b0d8" })
  hi(0, "LspReferenceRead", { link = "LspReferenceText" })
  hi(0, "LspReferenceText", { bg = "#161027" })
  hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
  hi(0, "LspSagaAutoPreview", { fg = "#c1b7de" })
  hi(0, "LspSagaBorderTitle", { link = "Title" })
  hi(0, "LspSagaCodeActionBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaCodeActionContent", { fg = "#c0aef4" })
  hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#f0b0d8" })
  hi(0, "LspSagaDefPreviewBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaDiagnosticBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
  hi(0, "LspSagaDiagnosticSource", { fg = "#fdb5a8" })
  hi(0, "LspSagaFinderSelection", { fg = "#93d1b5" })
  hi(0, "LspSagaHoverBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaLspFinderBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaRenameBorder", { fg = "#c1b7de" })
  hi(0, "LspSagaSignatureHelpBorder", { fg = "#c1b7de" })
  hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
  hi(0, "Macro", { fg = "#ccc3e4" })
  hi(0, "MasonError", { fg = "#ccc3e4" })
  hi(0, "MasonHeader", { bg = "#f0b0d8", bold = true, fg = "#1d172f" })
  hi(0, "MasonHeaderSecondary", { bg = "#c1b7de", bold = true, fg = "#1d172f" })
  hi(0, "MasonHeading", { link = "Bold" })
  hi(0, "MasonHighlight", { fg = "#c1b7de" })
  hi(0, "MasonHighlightBlock", { bg = "#c1b7de", fg = "#1d172f" })
  hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
  hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
  hi(0, "MasonHighlightBlockSecondary", { bg = "#f0b0d8", fg = "#1d172f" })
  hi(0, "MasonHighlightSecondary", { fg = "#f0b0d8" })
  hi(0, "MasonLink", { link = "MasonHighlight" })
  hi(0, "MasonMuted", { link = "Comment" })
  hi(0, "MasonMutedBlock", { bg = "#7a7094", fg = "#1d172f" })
  hi(0, "MasonMutedBlockBold", { bg = "#7a7094", bold = true, fg = "#1d172f" })
  hi(0, "MatchParen", { bg = "#161027", ctermbg = 6 })
  hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
  hi(0, "MiniAnimateNormalFloat", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "MiniClueBorder", { link = "NormalFloat" })
  hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
  hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
  hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
  hi(0, "MiniClueTitle", { bg = "#241e35", bold = true, fg = "#f0b0d8" })
  hi(0, "MiniCompletionActiveParameter", { bg = "#161027" })
  hi(0, "MiniCursorword", { underline = true })
  hi(0, "MiniCursorwordCurrent", { underline = true })
  hi(0, "MiniFilesBorder", { link = "NormalFloat" })
  hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
  hi(0, "MiniFilesDirectory", { link = "Directory" })
  hi(0, "MiniFilesFile", { fg = "#c0aef4" })
  hi(0, "MiniFilesNormal", { link = "NormalFloat" })
  hi(0, "MiniFilesTitle", { bg = "#241e35", fg = "#f0b0d8" })
  hi(0, "MiniFilesTitleFocused", { bg = "#241e35", bold = true, fg = "#f0b0d8" })
  hi(0, "MiniHipatterns161027", { bg = "#161027", fg = "#ffffff" })
  hi(0, "MiniHipatterns1d172f", { bg = "#1d172f", fg = "#ffffff" })
  hi(0, "MiniHipatterns241e35", { bg = "#241e35", fg = "#ffffff" })
  hi(0, "MiniHipatterns7a7094", { bg = "#7a7094", fg = "#ffffff" })
  hi(0, "MiniHipatterns806d91", { bg = "#806d91", fg = "#ffffff" })
  hi(0, "MiniHipatterns88cfdf", { bg = "#88cfdf", fg = "#000000" })
  hi(0, "MiniHipatterns8ba4e5", { bg = "#8ba4e5", fg = "#000000" })
  hi(0, "MiniHipatterns93d1b5", { bg = "#93d1b5", fg = "#000000" })
  hi(0, "MiniHipatterns9bc3f6", { bg = "#9bc3f6", fg = "#000000" })
  hi(0, "MiniHipatternsFixme", { bg = "#ccc3e4", bold = true, fg = "#1d172f" })
  hi(0, "MiniHipatternsHack", { bg = "#fdb5a8", bold = true, fg = "#1d172f" })
  hi(0, "MiniHipatternsNote", { bg = "#f0b0d8", bold = true, fg = "#1d172f" })
  hi(0, "MiniHipatternsTodo", { bg = "#9bc3f6", bold = true, fg = "#1d172f" })
  hi(0, "MiniHipatternsaf85b3", { bg = "#af85b3", fg = "#000000" })
  hi(0, "MiniHipatternsc0aef4", { bg = "#c0aef4", fg = "#000000" })
  hi(0, "MiniHipatternsc1b7de", { bg = "#c1b7de", fg = "#000000" })
  hi(0, "MiniHipatternsccc3e4", { bg = "#ccc3e4", fg = "#000000" })
  hi(0, "MiniHipatternsf0b0d8", { bg = "#f0b0d8", fg = "#000000" })
  hi(0, "MiniHipatternsf8c379", { bg = "#f8c379", fg = "#000000" })
  hi(0, "MiniHipatternsfdb5a8", { bg = "#fdb5a8", fg = "#000000" })
  hi(0, "MiniIndentscopeSymbol", { fg = "#c1b7de" })
  hi(0, "MiniIndentscopeSymbolOff", { fg = "#ccc3e4" })
  hi(0, "MiniJump", { link = "SpellRare" })
  hi(0, "MiniJump2dDim", { link = "Comment" })
  hi(0, "MiniJump2dSpot", { bg = "#241e35", bold = true, fg = "#806d91", nocombine = true })
  hi(0, "MiniJump2dSpotAhead", { bg = "#1d172f", fg = "#af85b3", nocombine = true })
  hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
  hi(0, "MiniMapNormal", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "MiniMapSymbolCount", { fg = "#9bc3f6" })
  hi(0, "MiniMapSymbolLine", { fg = "#f0b0d8" })
  hi(0, "MiniMapSymbolView", { fg = "#c1b7de" })
  hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
  hi(0, "MiniPickBorder", { link = "NormalFloat" })
  hi(0, "MiniPickBorderBusy", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "MiniPickBorderText", { bg = "#241e35", bold = true, fg = "#f0b0d8" })
  hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickIconDirectory", { link = "Directory" })
  hi(0, "MiniPickIconFile", { fg = "#c0aef4" })
  hi(0, "MiniPickMatchCurrent", { bg = "#161027" })
  hi(0, "MiniPickMatchMarked", { bg = "#7a7094" })
  hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
  hi(0, "MiniPickNormal", { link = "NormalFloat" })
  hi(0, "MiniPickPreviewLine", { bg = "#161027" })
  hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
  hi(0, "MiniPickPrompt", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "MiniStarterCurrent", { fg = "#c0aef4" })
  hi(0, "MiniStarterFooter", { fg = "#f0b0d8" })
  hi(0, "MiniStarterHeader", { fg = "#f0b0d8" })
  hi(0, "MiniStarterInactive", { link = "Comment" })
  hi(0, "MiniStarterItem", { fg = "#c0aef4" })
  hi(0, "MiniStarterItemBullet", { fg = "#c1b7de" })
  hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#ccc3e4" })
  hi(0, "MiniStarterQuery", { bold = true, fg = "#f8c379" })
  hi(0, "MiniStarterSection", { fg = "#c1b7de" })
  hi(0, "MiniStatuslineDevinfo", { bg = "#161027", fg = "#8ba4e5" })
  hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
  hi(0, "MiniStatuslineFilename", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
  hi(0, "MiniStatuslineModeCommand", { bg = "#ccc3e4", bold = true, fg = "#1d172f" })
  hi(0, "MiniStatuslineModeInsert", { bg = "#f0b0d8", bold = true, fg = "#1d172f" })
  hi(0, "MiniStatuslineModeNormal", { bg = "#c0aef4", bold = true, fg = "#1d172f" })
  hi(0, "MiniStatuslineModeOther", { bg = "#7a7094", bold = true, fg = "#1d172f" })
  hi(0, "MiniStatuslineModeReplace", { bg = "#fdb5a8", bold = true, fg = "#1d172f" })
  hi(0, "MiniStatuslineModeVisual", { bg = "#f8c379", bold = true, fg = "#1d172f" })
  hi(0, "MiniSurround", { link = "IncSearch" })
  hi(0, "MiniTablineCurrent", { bg = "#161027", bold = true, fg = "#c0aef4" })
  hi(0, "MiniTablineHidden", { bg = "#241e35", fg = "#8ba4e5" })
  hi(0, "MiniTablineModifiedCurrent", { bg = "#c0aef4", bold = true, fg = "#161027" })
  hi(0, "MiniTablineModifiedHidden", { bg = "#8ba4e5", fg = "#241e35" })
  hi(0, "MiniTablineModifiedVisible", { bg = "#8ba4e5", bold = true, fg = "#161027" })
  hi(0, "MiniTablineTabpagesection", { bg = "#93d1b5", bold = true, fg = "#241e35" })
  hi(0, "MiniTablineVisible", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "MiniTestEmphasis", { bold = true })
  hi(0, "MiniTestFail", { bold = true, fg = "#ccc3e4" })
  hi(0, "MiniTestPass", { bold = true, fg = "#f8c379" })
  hi(0, "MiniTrailspace", { link = "Error" })
  hi(0, "ModeMsg", { fg = "#f8c379" })
  hi(0, "MoreMsg", { ctermfg = 121, fg = "#f8c379" })
  hi(0, "MsgArea", { blend = 0, fg = "#c0aef4" })
  hi(0, "MsgSeparator", { blend = 0, fg = "#8ba4e5" })
  hi(0, "NeoTreeDimText", { fg = "#7a7094" })
  hi(0, "NeoTreeDotfile", { fg = "#8ba4e5" })
  hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
  hi(0, "NeoTreeFadeText2", { fg = "#161027" })
  hi(0, "NeoTreeGitAdded", { fg = "#f8c379" })
  hi(0, "NeoTreeGitConflict", { bold = true, fg = "#ccc3e4" })
  hi(0, "NeoTreeGitDeleted", { fg = "#ccc3e4" })
  hi(0, "NeoTreeGitModified", { fg = "#fdb5a8" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#ccc3e4" })
  hi(0, "NeoTreeGitUntracked", { fg = "#93d1b5" })
  hi(0, "NeoTreeMessage", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "NeoTreeModified", { fg = "#806d91" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#f0b0d8" })
  hi(0, "NeoTreeTabInactive", { fg = "#8ba4e5" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#161027", fg = "#7a7094" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#241e35", fg = "#241e35" })
  hi(0, "NeogitCommitViewHeader", { link = "Special" })
  hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
  hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
  hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
  hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
  hi(0, "NeogitFold", { link = "FoldColumn" })
  hi(0, "NeogitHunkHeader", { fg = "#f0b0d8" })
  hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#f0b0d8" })
  hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
  hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
  hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
  hi(0, "NoiceCmdline", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "NoiceCmdlineIcon", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconCalculator", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconCmdline", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconFilter", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconHelp", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconInput", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconLua", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlineIconSearch", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "NoiceCmdlinePopup", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "NoiceCmdlinePopupBorder", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderCalculator", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderCmdline", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderFilter", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderHelp", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderInput", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderLua", { fg = "#f0b0d8" })
  hi(0, "NoiceCmdlinePopupBorderSearch", { bg = "#241e35", fg = "#fdb5a8" })
  hi(0, "NoiceCmdlinePopupTitle", { bg = "#241e35", fg = "#9bc3f6" })
  hi(0, "NoiceCmdlinePrompt", { ctermfg = 225, fg = "#f0b0d8" })
  hi(0, "NoiceCompletionItemKindClass", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindColor", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindConstant", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindConstructor", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindDefault", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindEnum", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindEnumMember", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindField", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindFile", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindFolder", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindFunction", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindInterface", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindKeyword", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindMethod", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindModule", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindProperty", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindSnippet", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindStruct", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindText", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindUnit", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindValue", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceCompletionItemKindVariable", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceConfirm", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "NoiceConfirmBorder", { fg = "#fdb5a8" })
  hi(0, "NoiceCursor", { bg = "#c0aef4", fg = "#1d172f" })
  hi(0, "NoiceFormatConfirm", { bg = "#241e35" })
  hi(0, "NoiceFormatConfirmDefault", { bg = "#161027", ctermbg = 242 })
  hi(0, "NoiceFormatDate", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoiceFormatEvent", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceFormatKind", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceFormatLevelDebug", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceFormatLevelError", { ctermfg = 1, fg = "#ccc3e4" })
  hi(0, "NoiceFormatLevelInfo", { ctermfg = 4, fg = "#9bc3f6" })
  hi(0, "NoiceFormatLevelOff", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceFormatLevelTrace", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceFormatLevelWarn", { ctermfg = 3, fg = "#fdb5a8" })
  hi(0, "NoiceFormatProgressDone", { bg = "#93d1b5", fg = "#241e35" })
  hi(0, "NoiceFormatProgressTodo", { bg = "#241e35" })
  hi(0, "NoiceFormatTitle", { ctermfg = 225, fg = "#f0b0d8" })
  hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
  hi(0, "NoiceLspProgressClient", { ctermfg = 225, fg = "#f0b0d8" })
  hi(0, "NoiceLspProgressSpinner", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "NoiceLspProgressTitle", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "NoiceMini", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "NoicePopup", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "NoicePopupBorder", { bg = "#161027", fg = "#161027" })
  hi(0, "NoicePopupmenu", { bg = "#241e35", ctermbg = 13, ctermfg = 0, fg = "#c0aef4" })
  hi(0, "NoicePopupmenuBorder", { bg = "#161027", fg = "#161027" })
  hi(0, "NoicePopupmenuMatch", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "NoicePopupmenuSelected", { bg = "#c0aef4", ctermbg = 0, ctermfg = 242, fg = "#241e35" })
  hi(0, "NoiceScrollbar", { bg = "#161027", ctermbg = 248 })
  hi(0, "NoiceScrollbarThumb", { bg = "#806d91", ctermbg = 15 })
  hi(0, "NoiceSplit", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "NoiceSplitBorder", { bg = "#161027", fg = "#161027" })
  hi(0, "NoiceVirtualText", { ctermfg = 4, fg = "#9bc3f6" })
  hi(0, "NonText", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "Normal", { blend = 0, fg = "#c0aef4" })
  hi(0, "NormalFloat", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "NormalNC", { blend = 0, fg = "#c0aef4" })
  hi(0, "NotifyDEBUGBorder", { fg = "#7a7094" })
  hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
  hi(0, "NotifyERRORBorder", { fg = "#ccc3e4" })
  hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
  hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
  hi(0, "NotifyINFOBorder", { fg = "#9bc3f6" })
  hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
  hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
  hi(0, "NotifyTRACEBorder", { fg = "#f0b0d8" })
  hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
  hi(0, "NotifyWARNBorder", { fg = "#fdb5a8" })
  hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
  hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
  hi(0, "Number", { fg = "#88cfdf" })
  hi(0, "NvimTreeBookmark", { fg = "#f8c379" })
  hi(0, "NvimTreeExecFile", { bold = true, fg = "#f8c379" })
  hi(0, "NvimTreeFolderIcon", { fg = "#7a7094" })
  hi(0, "NvimTreeGitDeleted", { fg = "#ccc3e4" })
  hi(0, "NvimTreeGitDirty", { fg = "#ccc3e4" })
  hi(0, "NvimTreeGitMerge", { fg = "#9bc3f6" })
  hi(0, "NvimTreeGitNew", { fg = "#93d1b5" })
  hi(0, "NvimTreeGitRenamed", { fg = "#fdb5a8" })
  hi(0, "NvimTreeGitStaged", { fg = "#f8c379" })
  hi(0, "NvimTreeImageFile", { bold = true, fg = "#fdb5a8" })
  hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
  hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#fdb5a8" })
  hi(0, "NvimTreeLiveFilterValue", { bold = true })
  hi(0, "NvimTreeModifiedFile", { fg = "#f8c379" })
  hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
  hi(0, "NvimTreeRootFolder", { link = "NvimTreeGitRenamed" })
  hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#f0b0d8", underline = true })
  hi(0, "NvimTreeSymlink", { bold = true, fg = "#c1b7de" })
  hi(0, "NvimTreeWindowPicker", { bg = "#241e35", bold = true, fg = "#c0aef4" })
  hi(0, "Operator", { fg = "#c0aef4" })
  hi(0, "OutlineDetail", { fg = "#7a7094" })
  hi(0, "OutlineFoldPrefix", { fg = "#ccc3e4" })
  hi(0, "OutlineIndentEvn", { fg = "#8ba4e5" })
  hi(0, "OutlineIndentOdd", { fg = "#c0aef4" })
  hi(0, "Pmenu", { bg = "#241e35", ctermbg = 13, ctermfg = 0, fg = "#c0aef4" })
  hi(0, "PmenuSbar", { bg = "#161027", ctermbg = 248 })
  hi(0, "PmenuSel", { bg = "#c0aef4", ctermbg = 0, ctermfg = 242, fg = "#241e35" })
  hi(0, "PmenuThumb", { bg = "#806d91", ctermbg = 15 })
  hi(0, "PounceAccept", { bg = "#ccc3e4", bold = true, fg = "#1d172f", nocombine = true })
  hi(0, "PounceAcceptBest", { bg = "#f8c379", bold = true, fg = "#1d172f", nocombine = true })
  hi(0, "PounceGap", { bg = "#7a7094", bold = true, fg = "#1d172f", nocombine = true })
  hi(0, "PounceMatch", { bg = "#c0aef4", bold = true, fg = "#1d172f", nocombine = true })
  hi(0, "PreCondit", { fg = "#93d1b5" })
  hi(0, "PreProc", { ctermfg = 81, fg = "#93d1b5" })
  hi(0, "Question", { ctermfg = 121, fg = "#f0b0d8" })
  hi(0, "QuickFixLine", { bg = "#241e35" })
  hi(0, "RainbowDelimiterBlue", { fg = "#f0b0d8" })
  hi(0, "RainbowDelimiterCyan", { fg = "#9bc3f6" })
  hi(0, "RainbowDelimiterGreen", { fg = "#f8c379" })
  hi(0, "RainbowDelimiterOrange", { fg = "#88cfdf" })
  hi(0, "RainbowDelimiterRed", { fg = "#ccc3e4" })
  hi(0, "RainbowDelimiterViolet", { fg = "#fdb5a8" })
  hi(0, "RainbowDelimiterYellow", { fg = "#93d1b5" })
  hi(0, "References", { fg = "#f8c379" })
  hi(0, "ReferencesIcon", { fg = "#f0b0d8" })
  hi(0, "Repeat", { fg = "#93d1b5" })
  hi(0, "Search", { bg = "#93d1b5", ctermbg = 11, ctermfg = 0, fg = "#241e35" })
  hi(0, "SignColumn", { bg = "#241e35", ctermbg = 242, ctermfg = 14, fg = "#7a7094" })
  hi(0, "Sneak", { bg = "#fdb5a8", fg = "#1d172f" })
  hi(0, "SneakLabel", { bg = "#fdb5a8", bold = true, fg = "#1d172f" })
  hi(0, "SneakScope", { bg = "#806d91", fg = "#1d172f" })
  hi(0, "Special", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "SpecialChar", { fg = "#c1b7de" })
  hi(0, "SpecialComment", { fg = "#9bc3f6" })
  hi(0, "SpecialKey", { ctermfg = 81, fg = "#7a7094" })
  hi(0, "SpellBad", { ctermbg = 9, sp = "#ccc3e4", undercurl = true })
  hi(0, "SpellCap", { ctermbg = 12, sp = "#f0b0d8", undercurl = true })
  hi(0, "SpellLocal", { ctermbg = 14, sp = "#9bc3f6", undercurl = true })
  hi(0, "SpellRare", { ctermbg = 13, sp = "#fdb5a8", undercurl = true })
  hi(0, "Statement", { ctermfg = 11, fg = "#ccc3e4" })
  hi(0, "StatusLine", { bg = "#161027", fg = "#8ba4e5" })
  hi(0, "StatusLineNC", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "StorageClass", { fg = "#93d1b5" })
  hi(0, "String", { fg = "#f8c379" })
  hi(0, "Structure", { fg = "#fdb5a8" })
  hi(0, "Substitute", { bg = "#93d1b5", fg = "#241e35" })
  hi(0, "TabLine", { bg = "#241e35", ctermbg = 242, ctermfg = 15, fg = "#7a7094" })
  hi(0, "TabLineFill", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "TabLineSel", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "Tag", { fg = "#93d1b5" })
  hi(0, "TargetFileName", { fg = "#c0aef4" })
  hi(0, "TelescopeBorder", { fg = "#c1b7de" })
  hi(0, "TelescopeMatching", { fg = "#93d1b5" })
  hi(0, "TelescopeMultiIcon", { ctermfg = 14, fg = "#ccc3e4" })
  hi(0, "TelescopeMultiSelection", { bg = "#241e35", bold = true })
  hi(0, "TelescopeNormal", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopePreviewBlock", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewBorder", { fg = "#c1b7de" })
  hi(0, "TelescopePreviewCharDev", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewDate", { ctermfg = 159, fg = "#f0b0d8" })
  hi(0, "TelescopePreviewDirectory", { ctermfg = 159, fg = "#f0b0d8" })
  hi(0, "TelescopePreviewExecute", { fg = "#f8c379" })
  hi(0, "TelescopePreviewGroup", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewHyphen", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "TelescopePreviewLine", { bg = "#161027", ctermbg = 242 })
  hi(0, "TelescopePreviewLink", { ctermfg = 224, fg = "#9bc3f6" })
  hi(0, "TelescopePreviewMatch", { bg = "#93d1b5", ctermbg = 11, ctermfg = 0, fg = "#241e35" })
  hi(0, "TelescopePreviewMessage", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopePreviewMessageFillchar", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopePreviewNormal", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopePreviewPipe", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewRead", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewSize", { fg = "#f8c379" })
  hi(0, "TelescopePreviewSocket", { ctermfg = 11, fg = "#ccc3e4" })
  hi(0, "TelescopePreviewSticky", { fg = "#fdb5a8" })
  hi(0, "TelescopePreviewTitle", { fg = "#c1b7de" })
  hi(0, "TelescopePreviewUser", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopePreviewWrite", { ctermfg = 11, fg = "#ccc3e4" })
  hi(0, "TelescopePromptBorder", { fg = "#c1b7de" })
  hi(0, "TelescopePromptCounter", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "TelescopePromptNormal", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopePromptPrefix", { ctermfg = 14, fg = "#ccc3e4" })
  hi(0, "TelescopePromptTitle", { fg = "#c1b7de" })
  hi(0, "TelescopeResultsBorder", { fg = "#c1b7de" })
  hi(0, "TelescopeResultsClass", { fg = "#f0b0d8" })
  hi(0, "TelescopeResultsComment", { ctermfg = 14, fg = "#7a7094" })
  hi(0, "TelescopeResultsConstant", { ctermfg = 13, fg = "#88cfdf" })
  hi(0, "TelescopeResultsDiffAdd", { bg = "#241e35", ctermbg = 4, fg = "#f8c379" })
  hi(0, "TelescopeResultsDiffChange", { bg = "#241e35", ctermbg = 5, fg = "#fdb5a8" })
  hi(0, "TelescopeResultsDiffDelete", { bg = "#241e35", ctermbg = 6, ctermfg = 12, fg = "#ccc3e4" })
  hi(0, "TelescopeResultsDiffUntracked", { ctermfg = 12, fg = "#7a7094" })
  hi(0, "TelescopeResultsField", { fg = "#f0b0d8" })
  hi(0, "TelescopeResultsFunction", { fg = "#f0b0d8" })
  hi(0, "TelescopeResultsIdentifier", { ctermfg = 14, fg = "#ccc3e4" })
  hi(0, "TelescopeResultsLineNr", { bg = "#241e35", ctermfg = 11, fg = "#7a7094" })
  hi(0, "TelescopeResultsMethod", {})
  hi(0, "TelescopeResultsNormal", { bg = "#1d172f", fg = "#c0aef4" })
  hi(0, "TelescopeResultsNumber", { fg = "#88cfdf" })
  hi(0, "TelescopeResultsOperator", { fg = "#c0aef4" })
  hi(0, "TelescopeResultsSpecialComment", { fg = "#9bc3f6" })
  hi(0, "TelescopeResultsStruct", {})
  hi(0, "TelescopeResultsTitle", { fg = "#c1b7de" })
  hi(0, "TelescopeResultsVariable", { fg = "#c1b7de" })
  hi(0, "TelescopeSelection", { bg = "#241e35", bold = true })
  hi(0, "TelescopeSelectionCaret", { bg = "#241e35", bold = true })
  hi(0, "TelescopeTitle", { fg = "#c1b7de" })
  hi(0, "TermCursorNC", { reverse = true })
  hi(0, "Title", { ctermfg = 225, fg = "#f0b0d8" })
  hi(0, "Todo", { bg = "#241e35", ctermbg = 11, ctermfg = 0, fg = "#93d1b5" })
  hi(0, "TooLong", { fg = "#ccc3e4" })
  hi(0, "TroubleCount", { bold = true, fg = "#f8c379" })
  hi(0, "TroubleFoldIcon", { fg = "#c0aef4" })
  hi(0, "TroubleIndent", { fg = "#161027" })
  hi(0, "TroubleLocation", { fg = "#8ba4e5" })
  hi(0, "TroubleSignError", { link = "DiagnosticError" })
  hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
  hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
  hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
  hi(0, "TroubleText", { fg = "#c0aef4" })
  hi(0, "TroubleTextError", { link = "TroubleText" })
  hi(0, "TroubleTextHint", { link = "TroubleText" })
  hi(0, "TroubleTextInformation", { link = "TroubleText" })
  hi(0, "TroubleTextWarning", { link = "TroubleText" })
  hi(0, "Type", { ctermfg = 121, fg = "#93d1b5" })
  hi(0, "Typedef", { fg = "#93d1b5" })
  hi(0, "Underlined", { ctermfg = 81, underline = true })
  hi(0, "VertSplit", { blend = 0, fg = "#161027" })
  hi(0, "Visual", { bg = "#161027", ctermbg = 242 })
  hi(0, "VisualNOS", { fg = "#ccc3e4" })
  hi(0, "WarningMsg", { ctermfg = 224, fg = "#ccc3e4" })
  hi(0, "WhichKey", { fg = "#f0b0d8" })
  hi(0, "WhichKeyDesc", { fg = "#c0aef4" })
  hi(0, "WhichKeyFloat", { bg = "#241e35", fg = "#c0aef4" })
  hi(0, "WhichKeyGroup", { fg = "#fdb5a8" })
  hi(0, "WhichKeySeparator", { bg = "#241e35", fg = "#f8c379" })
  hi(0, "WhichKeyValue", { fg = "#7a7094" })
  hi(0, "Whitespace", { fg = "#7a7094" })
  hi(0, "WildMenu", { bg = "#93d1b5", ctermbg = 11, ctermfg = 0, fg = "#ccc3e4" })
  hi(0, "WinBar", { bg = "#161027", fg = "#8ba4e5" })
  hi(0, "WinBarNC", { bg = "#241e35", fg = "#7a7094" })
  hi(0, "WinSeparator", { blend = 0, fg = "#161027" })
  hi(0, "gitcommitBranch", { bold = true, fg = "#88cfdf" })
  hi(0, "gitcommitComment", { link = "Comment" })
  hi(0, "gitcommitDiscarded", { link = "Comment" })
  hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#ccc3e4" })
  hi(0, "gitcommitDiscardedType", { fg = "#f0b0d8" })
  hi(0, "gitcommitHeader", { fg = "#fdb5a8" })
  hi(0, "gitcommitOverflow", { fg = "#ccc3e4" })
  hi(0, "gitcommitSelected", { link = "Comment" })
  hi(0, "gitcommitSelectedFile", { bold = true, fg = "#f8c379" })
  hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitSummary", { fg = "#f8c379" })
  hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
  hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
  hi(0, "gitcommitUntracked", { link = "Comment" })
  hi(0, "gitcommitUntrackedFile", { fg = "#93d1b5" })
  hi(0, "lCursor", { bg = "#c0aef4", fg = "#1d172f" })
  hi(0, "lualine_a_command", { bg = "#e0d6fa", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_inactive", { bg = "#d3bfff", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_insert", { bg = "#ffd685", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_normal", { bg = "#d3bfff", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_replace", { bg = "#95e3f5", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_terminal", { bg = "#e0d6fa", bold = true, fg = "#1f1933" })
  hi(0, "lualine_a_visual", { bg = "#aad6ff", bold = true, fg = "#1f1933" })
  hi(0, "lualine_b_command", { bg = "#1f1933", fg = "#e0d6fa" })
  hi(0, "lualine_b_fancy_diff_added_command", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#1f1933", fg = "#f8c379" })
  hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#1f1933", fg = "#fdb5a8" })
  hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#1f1933", fg = "#ccc3e4" })
  hi(0, "lualine_b_inactive", { bg = "#1f1933", fg = "#d3bfff" })
  hi(0, "lualine_b_insert", { bg = "#1f1933", fg = "#ffd685" })
  hi(0, "lualine_b_normal", { bg = "#1f1933", fg = "#d3bfff" })
  hi(0, "lualine_b_replace", { bg = "#1f1933", fg = "#95e3f5" })
  hi(0, "lualine_b_terminal", { bg = "#1f1933", fg = "#e0d6fa" })
  hi(0, "lualine_b_visual", { bg = "#1f1933", fg = "#aad6ff" })
  hi(0, "lualine_c_command", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_fancy_cwd_command", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_inactive", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_insert", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_normal", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_replace", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_terminal", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_fancy_cwd_visual", { bg = "#18112a", fg = "#6ca6cd" })
  hi(0, "lualine_c_inactive", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_insert", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_normal", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_replace", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_terminal", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_c_visual", { bg = "#18112a", fg = "#d3bfff" })
  hi(0, "lualine_x_fancy_diagnostics_error_command", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_inactive", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_insert", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_normal", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_replace", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_terminal", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_error_visual", { bg = "#18112a", fg = "#ccc3e4" })
  hi(0, "lualine_x_fancy_diagnostics_hint_command", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_inactive", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_insert", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_normal", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_replace", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_terminal", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_hint_visual", { bg = "#18112a", fg = "#f0b0d8" })
  hi(0, "lualine_x_fancy_diagnostics_info_command", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_inactive", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_insert", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_normal", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_replace", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_terminal", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_info_visual", { bg = "#18112a", fg = "#9bc3f6" })
  hi(0, "lualine_x_fancy_diagnostics_warn_command", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_inactive", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_insert", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_normal", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_replace", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_terminal", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_fancy_diagnostics_warn_visual", { bg = "#18112a", fg = "#fdb5a8" })
  hi(0, "lualine_x_filetype_DevIconDefault_command", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_inactive", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_insert", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_normal", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_replace", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_terminal", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconDefault_visual", { bg = "#18112a", fg = "#6d8086" })
  hi(0, "lualine_x_filetype_DevIconLua_command", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_inactive", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_insert", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_normal", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_replace", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_terminal", { bg = "#18112a", fg = "#51a0cf" })
  hi(0, "lualine_x_filetype_DevIconLua_visual", { bg = "#18112a", fg = "#51a0cf" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#1d172f"
  g.terminal_color_1 = "#ccc3e4"
  g.terminal_color_2 = "#f8c379"
  g.terminal_color_3 = "#93d1b5"
  g.terminal_color_4 = "#f0b0d8"
  g.terminal_color_5 = "#fdb5a8"
  g.terminal_color_6 = "#9bc3f6"
  g.terminal_color_7 = "#c0aef4"
  g.terminal_color_8 = "#7a7094"
  g.terminal_color_9 = "#ccc3e4"
  g.terminal_color_10 = "#f8c379"
  g.terminal_color_11 = "#93d1b5"
  g.terminal_color_12 = "#f0b0d8"
  g.terminal_color_13 = "#fdb5a8"
  g.terminal_color_14 = "#9bc3f6"
  g.terminal_color_15 = "#806d91"
end

return set_colors
